services:
  - type: web
    name: django-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: false